apiVersion: jws.apache.org/v1alpha1
kind: Tomcat
metadata:
  name: example-tomcat
spec:
  applicationName: jws-app
  size: 2
  sourceRepositoryUrl: https://github.com/jboss-openshift/openshift-quickstarts.git
  sourceRepositoryRef: "1.2"
  contextDir: tomcat-websocket-chat
  jwsAdminUsername: tomcat
  jwsAdminPassword: tomcat
  githubWebhookSecret: tomcat
  genericWebhookSecret: tomcat
  imageStreamNamespace: openshift
  hostnameHttp: ""
  mavenMirrorUrl: ""
  artifactDir: ""
  replica: 1
